apiVersion: v1
kind: Pod
metadata:
  name: saps-archiver
  labels:
    app: saps-archiver
spec:
  containers:
  - name: archiver
    image: ufcgsaps/archiver
    volumeMounts:
    - name: archiverconf-volume
      mountPath: /archiver
  volumes:
  - name: archiverconf-volume
    configMap: 
      name: archiver-conf



    #volumes:
    #  - ./config/archiver.conf:/archiver/archiver.conf
    #  - ./config/log4j.properties:/archiver/log4j.properties
    #  - /nfs:/archiver/nfs

