apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  application.properties: |
    spring.jpa.database=POSTGRESQL
    spring.datasource.driverClassName=org.postgresql.Driver
    spring.datasource.platform=postgres
    spring.datasource.url=jdbc:postgresql://postgresql:5432/arrebol
    spring.datasource.username=postgres
    spring.datasource.password=admin1234
    spring.jpa.generate-ddl=true
    spring.jpa.hibernate.ddl-auto=update
  pgadmin.env: |
    PGADMIN_DEFAULT_EMAIL=admin@admin.com
    PGADMIN_DEFAULT_PASSWORD=admin1234
  postgres.env: |
    POSTGRES_PASSWORD=admin1234
  init.sql: |
    CREATE DATABASE arrebol;
  arrebol.json: |
    {
      "poolType":"docker",
      "properties":[
          {
            "key":"workerPoolSize",
            "value":5
          },
          {
            "key":"imageId",
            "value":"wesleymonte/simple-worker"
          },
          {
            "key":"resourceAddresses",
            "value":[
                "http://127.0.0.1:5555"
            ]
          }
      ]
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: saps-arrebol
  labels:
    app: saps-arrebol
spec:
  containers:
  # Container for postgres DB
  - name: postgresql
    image: postgres
    env:
    - name: POSTGRES_PASSWORD
      value: "admin1234"
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: postgres-volume
    - mountPath: /docker-entrypoint-initdb.d/
      name: arrebolconf-volume
    ports:
    - containerPort: 5432
  # Container for pgadmin
  - name: pgadmin
    image: dpage/pgadmin4
    env:
    - name: PGADMIN_DEFAULT_EMAIL
      value: "admin@admin.com"
    - name: PGADMIN_DEFAULT_PASSWORD
      value: "admin1234"
    ports:
    - containerPort: 15432
  # Main container of Arrebol
  - name: arrebol
    image: ufcglsd/arrebol:saps
    volumeMounts:
    - name: arrebolconf-volume
      mountPath: /service/config/
    ports:
    - containerPort: 8080
  volumes:
  - name: arrebolconf-volume
    configMap: 
      name: arrebol-config
  - name: postgres-volume
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: saps-arrebol
spec:
  selector:
    app: saps-arrebol
  ports:
  - name: arrebol
    protocol: TCP
    port: 8080
    targetPort: 8080
