apiVersion: v1
kind: ConfigMap
metadata:
  name: arrebol-config
data:
  application.properties: |
    spring.jpa.database=POSTGRESQL
    spring.datasource.driverClassName=org.postgresql.Driver
    spring.datasource.platform=postgres
    spring.datasource.url=jdbc:postgresql://localhost:5432/arrebol
    spring.datasource.username=postgres
    spring.datasource.password=admin1234
    spring.jpa.generate-ddl=true
    spring.jpa.hibernate.ddl-auto=update
  arrebol.json: |
    {
      "poolType":"docker",
      "properties":[
          {
            "key":"workerPoolSize",
            "value":5
          },
          {
            "key":"imageId",
            "value":"wesleymonte/simple-worker"
          },
          {
            "key":"resourceAddresses",
            "value":[
                "http://127.0.0.1:5555"
            ]
          }
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  PGADMIN_DEFAULT_EMAIL: admin@admin.com
  PGADMIN_DEFAULT_PASSWORD: admin1234
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin1234
  POSTGRES_DB: arrebol
---
apiVersion: v1
kind: Pod
metadata:
  name: saps-arrebol
  labels:
    app: saps-arrebol
spec:
  containers:
  # Container for postgres DB
  - name: postgresql
    image: postgres
    envFrom:
    - configMapRef:
        name: postgres-config
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: postgres-volume
    ports:
    - containerPort: 5432
  # Container for pgadmin
  - name: pgadmin
    image: dpage/pgadmin4
    envFrom:
    - configMapRef:
        name: pgadmin-config
    ports:
    - containerPort: 15432
  # Main container of Arrebol
  - name: arrebol
    image: ufcglsd/arrebol:saps
    volumeMounts:
    - name: arrebolconf-volume
      mountPath: /service/config/
    ports:
    - containerPort: 8080
  volumes:
  - name: arrebolconf-volume
    configMap: 
      name: arrebol-config
  - name: postgres-volume
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: saps-arrebol
spec:
  selector:
    app: saps-arrebol
  ports:
  - name: arrebol
    protocol: TCP
    port: 8080
    targetPort: 8080
