apiVersion: v1
kind: Pod
metadata:
  name: saps-catalog
  labels:
    app: saps-catalog
spec:
  containers:
  - name: catalog
    image: ufcgsaps/catalog
    imagePullPolicy: Always
    env:
    - name: POSTGRES_USER
      value: "admin"
    - name: POSTGRES_PASSWORD
      value: "admin"
    - name: POSTGRES_DB
      value: "saps"
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: catalog-volume
    ports:
    - containerPort: 5432
  volumes:
  - name: catalog-volume
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: saps-catalog
spec:
  selector:
    app: saps-catalog
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
