apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatcher-config
data:
  dispatcher.conf: |
    datastore_url_prefix=jdbc:postgresql://
    datastore_ip=<catalog_ip>
    datastore_port=5432
    datastore_name=saps
    datastore_driver=org.postgresql.Driver
    datastore_username=admin
    datastore_password=admin
    permanent_storage_tasks_dir=archiver
    permanent_storage_debug_tasks_dir=trash
    openstack_identity_service_api_url=https://horsemen.i3m.upv.es:5000
    openstack_project_id=$project_id
    openstack_user_id=$user_id
    openstack_user_password=$pass
    openstack_object_store_service_api_url=http://horsemen.i3m.upv.es:8080/v1/AUTH_1e2861bec8174318b8002ac897e21aef
    openstack_object_store_service_container_name=saps
    openstack_object_store_service_key=1a2b3c4d
    nfs_permanent_storage_path=/nfs
    permanent_storage_base_url=http://<nfsserver_ip>:80/archiver
    submission_rest_server_port=8091
    admin_email=adminemail@domain
    admin_user=admin
    admin_password=admin1234
    noreply_email=$noreply_email
    noreply_password=$noreply_password
    saps_temp_storage_path=/var/tmp/nfsaps/
    saps_permanent_storage_type=swift
    saps_debug_mode=true
  log4j.properties: |
    log4j.rootLogger=DEBUG, file, stdout
    log4j.category.org.restlet=INFO
    log4j.category.org.apache.http=INFO
    log4j.appender.DatePattern='.'yyyy-MM-dd
    log4j.appender.file=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.file.File=/var/tmp/saps-engine/logs/log4j.log
    log4j.appender.file.layout=org.apache.log4j.PatternLayout
    log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: executor-config
data:
  execution_script_tags.json: |
    {
        "processing":[
          {
            "name":"ufcg-sebal",
            "docker_tag":"ufcg-sebal",
            "docker_repository":"fogbow/worker"
          },{
            "name":"sebkc-sebal",
            "docker_tag":"sebkc-sebal",
            "docker_repository":"fogbow/worker"
          },{
            "name":"sebkc-tseb",
            "docker_tag":"sebkc-tseb",
            "docker_repository":"fogbow/worker"
          }
        ],
        "preprocessing":[
          {
            "name":"default",
            "docker_tag":"default",
            "docker_repository":"fogbow/preprocessor"
          },{
            "name":"legacy",
            "docker_tag":"legacy",
            "docker_repository":"fogbow/preprocessor"
          }
        ],
        "inputdownloading":[
          {
            "name":"usgsapis",
            "docker_tag":"usgsapis",
            "docker_repository":"fogbow/inputdownloader"
          },{
            "name":"googleapis",
            "docker_tag":"googleapis",
            "docker_repository":"fogbow/inputdownloader"
          }
        ]
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-saps-dispatcher
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      name: "nfs"
  storageClassName: nfs
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: saps-dispatcher
  labels:
    app: saps-dispatcher
spec:
  containers:
  - name: dispatcher
    image: ufcgsaps/dispatcher
    volumeMounts:
    - name: dispatcherconf-volume
      mountPath: /dispatcher
    - name: executorconf-volume
      mountPath: /dispatcher/resources
    - name: nfs-dispatcher
      mountPath: "/dispatcher/nfs"
    ports:
    - containerPort: 8091
  volumes:
  - name: dispatcherconf-volume
    configMap: 
      name: dispatcher-config
  - name: executorconf-volume
    configMap: 
      name: executor-config
  - name: nfs-dispatcher
    persistentVolumeClaim:
      claimName: nfs-saps-dispatcher
---
apiVersion: v1
kind: Service
metadata:
  name: saps-dispatcher
spec:
  selector:
    app: saps-dispatcher
  ports:
  - name: dispatcher
    protocol: TCP
    port: 8091
    targetPort: 8091