apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-job-test
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      name: "nfs"
  storageClassName: nfs
  resources:
    requests:
      storage: 10Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: saps-job
spec:
  template:
    spec:
      containers:
        - name: test-job-saps
          image: fogbow/inputdownloader:nop-fake-files
          command: [ "/bin/sh", "-c", "/home/saps/run.sh /nfs landsat_8 215065 2015-06-23" ]
          volumeMounts:
            - name: nfs-test
              mountPath: /nfs
      restartPolicy: Never

      volumes:
      - name: nfs-test
        persistentVolumeClaim:
          claimName: nfs-job-test