apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  #storageClassName: local-storage
  selector:
    matchLabels:
      name: "nfs"
  resources:
    requests:
      storage: 100Mi