apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  accessModes:
    - ReadWriteMany
  #storageClassName: ""
  resources:
    requests:
      storage: 100Mi