  
version: '3.7'
services:
  catalog:
    image: ufcgsaps/catalog
    env_file: ./config/catalog.env
    ports: 
      - 5432:5432
    networks: 
      - saps-network
    volumes: 
      - catalogdata:/var/lib/postgresql/data
      
  dispatcher:
    image: ufcgsaps/dispatcher
    ports:
      - 8091:8091
    networks: 
      - saps-network
    volumes:
      - ./config/dispatcher.conf:/etc/saps/dispatcher.conf
      - ./config/log4j.properties:/etc/saps/log4j.properties
      - ./config/execution_script_tags.json:/dispatcher/resources/execution_script_tags.json
      - /nfs:/dispatcher/nfs
  
  scheduler:
    image: ufcgsaps/scheduler
    networks: 
      - saps-network
    volumes:
      - ./config/scheduler.conf:/etc/saps/scheduler.conf
      - ./config/log4j.properties:/etc/saps/log4j.properties
      - ./config/execution_script_tags.json:/scheduler/resources/execution_script_tags.json
    
  archiver:
    image: ufcgsaps/archiver
    networks:
      - saps-network
    volumes:
      - ./config/archiver.conf:/etc/saps/archiver.conf
      - ./config/log4j.properties:/etc/saps/log4j.properties
      - /nfs:/archiver/nfs

volumes:
  catalogdata: {}

networks:
  saps-network:
    driver: overlay